### ISSUE TITLE
contract storage not modified / always empty

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/ethereum.js#110]
Using the following example: https://gist.github.com/jorisbontje/8723e4f32eb523fd8e8f
using cpp-ethereum develop commit https://github.com/ethereum/cpp-ethereum/commit/bb150eae4383c340908b7a4ce9351a4334fcac50
Starting `eth -j -s 0xc85ef7d79691fe79573b1a7064c19c1a9819ebdbd1faaab1a8ec92344438aaf4 -m on`

When trying to access the contract storage, after triggering the `inc` function a couple times, `getStorage` always returns an empty object. `getData` does return the contracts' code.
`eth` log contains no error messages...

I would expect that `getStorage` would return the storage value instead.

**Comment by frozeman** [comment]
thats probably an issue with the rpc. I'm currently writing test for it, i guess i will soon stumble upon this myself.

**Comment by gavofyork** [comment]
`getStorageAt` should be used, not plain `getStorage`.

**Comment by gavofyork** [comment]
this should be fixed in latest develop.
