### ISSUE TITLE
Filter on address also triggered on generic block updates

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/ethereum.js#123]
When I setup a filter on my contract address, it is also triggered by generic block updates (address = 0x00000...). I would expect only messages containing an exact match of the specified address.

```
web3.eth.filter({'address': myContractAddress}).watch(function(res) {
                console.log(res);
});
```

From the console log:
```
Object {address: "0x0000000000000000000000000000000000000000", data: "0x", hash: "0x0000000000000000000000000000000000000000000000000000000000000000", number: 0, topics: Array[0]}address: "0x0000000000000000000000000000000000000000"data: "0x"hash: "0x0000000000000000000000000000000000000000000000000000000000000000"number: 0topics: Array[0]__proto__: Object
```

This is with cpp-ethereum develop 1e02011 and ethereum.js develop 8c36a10e7d976f088242d1e04f2a3fb6abbf1b76

**Comment by debris** [comment]
please check if it still occurs

**Comment by debris** [comment]
If the issue still occurs, please reopen on cpp-ethereum.
