### ISSUE TITLE
from is mandatory for sendTransaction

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/ethereum.js#124]
According to @fjl the `from` argument is mandatory for `sendTransaction`. If this is missing in the `sendTransaction` call I would expect an error. Probably also nice to indicate on https://github.com/ethereum/wiki/wiki/JavaScript-API which arguments are mandatory and which aint.

https://github.com/ethereum/go-ethereum/issues/490#issuecomment-81589978

**Comment by fjl** [comment]
What is this issue about?

**Comment by jorisbontje** [comment]
@fjl this issue is about from being mandatory for sendTransaction according to you. This currently isn't enforced by ethereum.js nor specified in the JS docs.

**Comment by SilentCicero** [comment]
Agreed, this is confusing and should be specified.

**Comment by debris** [comment]
I've updated the docs. `from` is mandatory for `sendTransaction`. Although implementations are allowed to be lenient.
