### ISSUE TITLE
Make consistent the allowable formats for numbers

### ISSUE THREAD

**Issue by ethers** [ethereum/ethereum.js#129]
https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendtransaction says `gas (integer), the amount of gas to purchase for the transaction`. but gasPrice can be specified in other formats:
`gasPrice (number|hexString|BigNumber), the price of gas for this transaction in wei`

Should be fixed for consistency, imho all should accept the different formats (number|hexString|BigNumber), and the code and wiki updated.  (#128 is an example of code fix probably needed)

**Comment by debris** [comment]
fixed && updated docs
