### ISSUE TITLE
It would be helpful if there was a forum section on forum.ethereum.org specific to ethereumjs

### ISSUE THREAD

**Issue by drcode** [ethereum/ethereum.js#132]
Currently there is no forum to ask questions specific to ethereumjs questions. Please create a section on forum.ethereum.org for this purpose.

**Comment by chevdor** [comment]
A Gitter was just created, could that satisfy your request ? (See #138)
You may find it here:
[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/ethereum/ethereum.js?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by drcode** [comment]
Yes, let's give it a try!
