### ISSUE TITLE
web3.eth.filter / watch documentation

### ISSUE THREAD

**Issue by ethers** [ethereum/ethereum.js#136]
Please review and update the JS API and JSONRPC docs.  Here are some examples.

https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getfilterchanges
- [x] response is missing topics

https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter
- [x] filter('latest').watch behavior is not clarified, eg https://github.com/ethereum/cpp-ethereum/issues/1361
- [x] is 'fromBlock' valid like web3.eth.filter({'fromBlock': 'latest'}).watch  see https://github.com/ethereum/cpp-ethereum/issues/1368

Please also clarify required format/lengths of data, eg when is "0x0" required vs "0x0000000000000000000000000000000000000000000000000000000000000000"

More examples of filter/watch could also be more helpful to the community.

**Comment by SilentCicero** [comment]
Agreed, and similarly the Frontier docs feature a MultiplyContract example usage that is incorrect, contract.sendTransaction().multiply(##) should be contract.call().multiply(##).

**Comment by drcode** [comment]
Agreed

**Comment by debris** [comment]
> Agreed, and similarly the Frontier docs feature a MultiplyContract example usage that is incorrect...

@SilentCicero what docs are you talking about? Please give me a link ;)

**Comment by debris** [comment]
`latest` should be used to be notified about new block. I've updated json-rpc docs
