### ISSUE TITLE
Fatal: Error requiring web3: Cannot find module 'web3'

### ISSUE THREAD

**Issue by zelig** [ethereum/ethereum.js#143]
tried to use the latest develop branch `ethereum-light.min.js`but the jsre says:

```
Fatal: Error requiring web3: Cannot find module 'web3'
```
when i `require web3` . this used to work but not sure yet if this is jsre issue or ethereum.js

**Comment by frozeman** [comment]
@debris can you take a look?

**Comment by debris** [comment]
I'm 90% sure, that this is jsre issue. I will take a closer look at this today.

**Comment by frozeman** [comment]
it worked before as far as i know

**Comment by zelig** [comment]
will fix in go-ethereum https://github.com/ethereum/go-ethereum/issues/558
