### ISSUE TITLE
getBalance in ethereum-light.js from sandbox branch accepts only decimal addresses

### ISSUE THREAD

**Issue by nagydani** [ethereum/ethereum.js#144]
To reproduce, try this:
```
> web3.eth.getBalance('dbdbdb2cbd23b783741e8d7fcf51e459b497e4a6').toNumber()
0
> web3.eth.getBalance('0xdbdbdb2cbd23b783741e8d7fcf51e459b497e4a6').toNumber()
0
> web3.eth.getBalance('1255171934823351805979544608257289442498956485798').toNumber()
1.6069380442589903e+60
```

**Comment by frozeman** [comment]
thats odd. Etheruem.js is just passing it through to the RPC. It can be that the hex is in go converted to this weird byte array we saw before and then passed to the RPC. Can you guys check?

**Comment by zsfelfoldi** [comment]
I'll check. But it works fine with the ethereum.js from the main branch.

**Comment by frozeman** [comment]
hm..

**Comment by debris** [comment]
any update on this?

**Comment by zsfelfoldi** [comment]
Well, in last thursday's develop version it worked fine. In the latest version it seems to be wrong again. Drives me crazy, now i'm comparing these two.

**Comment by debris** [comment]
in e213551699cd10e6ef2f5fd7a43dbc6e01ad0ad8 I added few tests for `0xdbdbdb2cbd23b783741e8d7fcf51e459b497e4a6` && `1255171934823351805979544608257289442498956485798`. They are passing and `web3.eth.balance` should be working fine. If it is not, it's otto JSRE or go-ethereum internal issue. If it's required I investigate the possibilities of running tests directly in the go-etheruem jsre.

**Comment by zsfelfoldi** [comment]
My bad, it works fine now, something else was wrong when I tried it last time.
