### ISSUE TITLE
JSON-RPC id not incrementing

### ISSUE THREAD

**Issue by cubedro** [ethereum/ethereum.js#147]
{ jsonrpc: '2.0', method: 'net_peerCount', params: [], id: 1 }
{"id":1,"jsonrpc":"2.0","result":"0x5"}

{ jsonrpc: '2.0', method: 'eth_blockNumber', params: [], id: 1 }
{"id":1,"jsonrpc":"2.0","result":"0x841b"}

{ jsonrpc: '2.0', method: 'eth_mining', params: [], id: 1 }
{"id":1,"jsonrpc":"2.0","result":false}

{ jsonrpc: '2.0', method: 'eth_gasPrice', params: [], id: 1 }
{"id":1,"jsonrpc":"2.0","result":"0x09184e72a000"}

{ jsonrpc: '2.0', method: 'net_listening', params: [], id: 1 }
{"id":1,"jsonrpc":"2.0","result":true}

{ jsonrpc: '2.0',
  method: 'eth_newBlockFilter',
  params: [ 'pending' ],
  id: 1 }
{"id":1,"jsonrpc":"2.0","result":"0x4"}

{ jsonrpc: '2.0',
  method: 'eth_newBlockFilter',
  params: [ 'latest' ],
  id: 1 }
{"id":1,"jsonrpc":"2.0","result":"0x5"}

**Comment by debris** [comment]
You are right.
But I would still prefer to use `arguments.calle`. I just forgot to add `arguments.callee._singletonInstance = this;`.

```
    if (arguments.callee._singletonInstance) {
        return arguments.callee._singletonInstance;
    }
    arguments.callee._singletonInstance = this;
```

docs:
https://code.google.com/p/jslibs/wiki/JavascriptTips#Singleton_pattern

I will also add appropriate tests for it
