### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by ethers** [ethereum/ethereum.js#152]
Using ethereum.js develop c80ede5

Run Geth develop branch 607fc78

Loading dapp page is now giving this error in the browser JS console:
```
XMLHttpRequest cannot load http://localhost:8080/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.
```

**Comment by obscuren** [comment]
That's becuase `geth` set cors to "" (I.e. Not allowed). Run `geth --rpccorsdonain localhost` and you'll be good to go

**Comment by kingflurkel** [comment]
Little typo in the answer; --rpccorsdomain
