### ISSUE TITLE
Cannot find module 'web3'

### ISSUE THREAD

**Issue by forgetso** [ethereum/ethereum.js#17]
I've created a folder called 'eth' and a folder called 'node_modules' within it. I run

`npm install ethereum.js`

from within 'eth' and ethereum.js is installed to node_modules.

Running a simple test.js file containing

`require('web3');
console.log('hiya');`

returns the error

`Cannot find module 'web3'`

Are there any workarounds for this?

**Comment by kumavis** [comment]
`var web3 = require('ethereum.js') `

see https://github.com/ethereum/ethereum.js/pull/14
