### ISSUE TITLE
convert type differences between cpp-ethereum and go-ethereum

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/ethereum.js#24]
When calling `eth_balanceAt`, cpp-ethereum returns a hexidecimal string, while the go-ethereum client returns a string with a decimal number inside. The laters fails when converting this to a decimal in the https://github.com/ethereum/ethereum.js/blob/master/example/balance.html example.

**Comment by frozeman** [comment]
same for gasPrice and gas

**Comment by debris** [comment]
@see [rpc-tests](https://github.com/ethereum/rpc-tests)

**Comment by debris** [comment]
all the rpc methods are unified and working fine now. If there are still problems with endpoints, please create new issue for each one of them.
