### ISSUE TITLE
array support

### ISSUE THREAD

**Issue by ethers** [ethereum/ethereum.js#30]
need to be able to call contracts where some input parameters are arrays.

please add an example too, or extend 
https://github.com/ethereum/ethereum.js/blob/develop/example/contract.html

**Comment by debris** [comment]
done on develop branch, will add examples soon

**Comment by debris** [comment]
in ethereum.js everything should be ready to support arrays now. here is an [example](https://github.com/ethereum/ethereum.js/blob/master/example/contract_with_array.html). Unfortunately, arrays are not yet supported in solidity. I've created an [issue for that in cpp-ethereum repo](https://github.com/ethereum/cpp-ethereum/issues/905).

**Comment by ethers** [comment]
was the following fixed?
… var bethAbi = [
  {
    'name': 'callsA',
    'constant': false,
    'inputs': [{
      'name': 'n',
      'type': 'int[]'
    },
    {
      'name': 'x',
      'type': 'uint256'
    }],
    'outputs': [
        {
            "name": "d",
            "type": "uint256"
        }
    ]
  }
];
it should be <arrayLength><value of x><contents of array n>
ethereum.js does <arrayLength><contents of array n><value of x>

**Comment by ethers** [comment]
fixed https://github.com/ethereum/ethereum.js/pull/81
