### ISSUE TITLE
[mist] TypeError: undefined is not a constructor (evaluating 'new web3.providers.QtProvider()')

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/ethereum.js#38]
Trying `example/balance.html` gives the following error:
TypeError: undefined is not a constructor (evaluating 'new web3.providers.QtProvider()')

![screen shot 2015-01-20 at 11 25 45](https://cloud.githubusercontent.com/assets/620959/5815609/44678a38-a097-11e4-836b-d49c288f24cb.png)

This is with Mist 0.8.1 (go1.4.1) on OSX, commit 06bfe19f05b2a961a458cada69c72c809354f53f and Ethereum.JS commit 6a58db66f7f42a49667bcc751418256441752279

**Comment by klkim** [comment]
Using web3.providers.QtSyncProvider() not web3.providers.QtProvider()

**Comment by kumavis** [comment]
@jorisbontje this is out of date so I'm going to close the issue - feel free to reopen it if you're still stuck here
