### ISSUE TITLE
web3.contract not documented

### ISSUE THREAD

**Issue by kumavis** [ethereum/ethereum.js#39]
api: https://github.com/ethereum/wiki/wiki/JavaScript-API
contract: https://github.com/ethereum/ethereum.js/blob/master/lib/contract.js

**Comment by debris** [comment]
done
api: https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcontract
contract: https://github.com/ethereum/ethereum.js/blob/master/lib/contract.js#L26-L46

**Comment by kumavis** [comment]
cheers!
