### ISSUE TITLE
CORS headers are missing on RPC cpp endpoints

### ISSUE THREAD

**Issue by frozeman** [ethereum/ethereum.js#41]
I get CORS errors when i want to connect to `eth` node started with `$ eth -j -b -f -n no -m yes` in safari:

```js
[Error] XMLHttpRequest cannot load http://localhost:8080/. Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin.
	send (ethereum.js, line 660)
	send (ethereum.js, line 746)
	(anonymous function) (ethereum.js, line 967)
	(anonymous function) (whisperConnector.js, line 16)
	global code (whisperConnector.js, line 208)
[Error] Failed to load resource: Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin. (localhost, line 0)
```

The RPC endpoint should return CORS headers, probably even for OPTIONS pre-flight requests.

Works in chrome, thought...

This should probably go to the CPP repo?

**Comment by kumavis** [comment]
opening up to CORS should be a configuration option on all clients.
it should not be on by default as that is a security issue.
currently `node-ethereum` has CORS support,
but I can't speak to current state of the project

**Comment by jorisbontje** [comment]
@frozeman I noticed the same thing: https://github.com/ethereum/cpp-ethereum/issues/870

**Comment by kumavis** [comment]
On a related note, we should also make a generic RPC test suite that runs offline or in a web-browser and hits a specified client

**Comment by debris** [comment]
should be fixed in latest cpp-ethereum develop
