### ISSUE TITLE
XMLHttpRequest cannot load http://127.0.0.1:30303/

### ISSUE THREAD

**Issue by scottzer0** [ethereum/ethereum.js#46]
i'm getting a cross-domain issue when using the HttpSyncProvider.  are we not using a jsonp technique here to allow different origins?

i'm trying to develop a UI that will probably be hosted from a CDN or external source and connect to the local ethereum client.  websockets i understand are being deprecated.

**Comment by debris** [comment]
so, by default jsonrpc server is available at port 8080, not 30303. You can start it by running `eth -j -b`, where `-j` is responsible for starting jsonrpc server && `-b`  for connecting to the default Ethereum peerserver.

But it's true that there is an issue with cross-domain support. This will be fixed soon. I've [opened issue](https://github.com/ethereum/cpp-ethereum/issues/882) for that in cpp-ethereum repo.
