### ISSUE TITLE
Trying to connect to WebSocketProvider, but function has been removed from repo

### ISSUE THREAD

**Issue by drcode** [ethereum/ethereum.js#49]
Hi, your README suggests using providers.WebSocketProvider, but this function was removed recently (at lease it no longer exists in the ethereum.js in the repo's "dist" folder)

Is there still a way to connect to the go ethereum websocket? If not, what is now the proper procedure for connecting to the go ethereum CLI? (Exact info would be helpful, like what go ethereum args are needed, and what port # is used, and what new connection function should be used...)

**Comment by ryansundberg** [comment]
It's commented out from the source, probably you're best off sticking with the simpler HTTP API for a while.
