### ISSUE TITLE
Version tags for Bower?

### ISSUE THREAD

**Issue by simondlr** [ethereum/ethereum.js#65]
Hi.

I'm using to fetch ethereum.js. Firstly, it seems to be @cubedro's repo (not this one), and there aren't any version tags.

Would be nice to set a version in bower.json to ensure if someone else wants to develop, they don't download another version of ethereum.js that might not be compatible.

---

bower ethereum.js#0.0.15    not-cached git://github.com/cubedro/ethereum.js.git#0.0.15
bower ethereum.js#0.0.15       resolve git://github.com/cubedro/ethereum.js.git#0.0.15
bower ethereum.js#0.0.15  ENORESTARGET No tag found that was able to satisfy 0.0.15

Additional error details:
No versions found in git://github.com/cubedro/ethereum.js.git

**Comment by simondlr** [comment]
You can use hashes, but it would be cleaner with version tags. :)

**Comment by debris** [comment]
We will fix this with new release (~7-10 days from now). Some methods are going to be [renamed](https://github.com/ethereum/wiki/wiki/JavaScript-API), but we should have backwards compatibility by marking old ones as deprecated.

**Comment by simondlr** [comment]
Thanks!

**Comment by cubedro** [comment]
Fixed

**Comment by simondlr** [comment]
Thanks for adding them!

**Comment by cubedro** [comment]
np ;)
