### ISSUE TITLE
TypeError: 'undefined' is not a function (evaluating 'navigator.qt.callMethod(JSON.stringify(t))')

### ISSUE THREAD

**Issue by novusopt** [ethereum/ethereum.js#66]
Hi,
i am getting this error in line 573 in ethereum.min.js
Here is my html file:
![html_balance_file](https://cloud.githubusercontent.com/assets/860239/6247554/24a3ce78-b776-11e4-9972-0b037667375c.png)

And here the error message
![ethereum_error](https://cloud.githubusercontent.com/assets/860239/6247562/391e03b4-b776-11e4-95b6-f681155d9b08.png)

Debug info from Mist
![debug_info](https://cloud.githubusercontent.com/assets/860239/6247754/84b33612-b778-11e4-9d44-89ced3fd7493.png)

**Comment by simondlr** [comment]
Promises have been deprecated. You can't do "then" anymore.

**Comment by fouadaberkane** [comment]
Thank you. 
I have a comprehension question what is a provider (QtSyncProvider and HttpSyncProvider)
what ist the conecpt and what is required to connect from the browser for instance when i choose HttpSyncprovider (url + port).

**Comment by kumavis** [comment]
@novusopt web3 needs to be backed by an RPC. Connections to that rpc can be made via http-sync and via qt bindings (c++ client only). HttpSyncProvider connects the web3 calls into http requests against the rpc. You'll need to run an rpc client, such as `go-ethereum`. You'll likely need to enable rpc via flags.

I'm going to close this issue for now, if you have additional questions feel free to ask.

**Comment by kumavis** [comment]
If you're developing a dapp in Mist, you'll want to setup web3 in this way:
```js
var web3 = require('web3');
web3.setProvider(new web3.providers.HttpSyncProvider('http://localhost:8545'));
```
