### ISSUE TITLE
ethereum.js doesn't provide a way to create contract with nondefault constructor

### ISSUE THREAD

**Issue by debris** [ethereum/ethereum.js#70]

**Comment by psalami** [comment]
+1

**Comment by debris** [comment]
there are now multiple ways of creating contract:


var code = `0x600080547fffffffffffffffffffffffff000000000000000000000000000000000000000016331790556105c7806100386000396000f3007c0100000000000000000000000000';

var address = web3.eth.sendTransaction({data: code}); // creates new contract on a blockchain
console.log(address); //  '0x1234567890123456789012345678901234567890';

var Contract = web3.eth.contract(abi)
var a = new Contract(address);  // uses existing ethereum contract, doesn't create new contract on a blockchain
var b = new Contract (code); // creates new contract on a blockchain
var c = new Contract (code, 2, 4); // creates new contract on a blockchain using non default constructor (int, int)
