### ISSUE TITLE
todo to remove prior to genesis

### ISSUE THREAD

**Issue by ethers** [ethereum/ethereum.js#72]
Is there a way such issues are already being tracked, so that they are not forgotten among all the activity that will happen during genesis launch?
https://github.com/ethereum/ethereum.js/blob/develop/lib/web3.js#L168

**Comment by debris** [comment]
just the community creating issues here

**Comment by kumavis** [comment]
@ethers do you have additional questions about this, or is it ok to close?

**Comment by ethers** [comment]
it is still there so I don't think it should be closed: https://github.com/ethereum/ethereum.js/blob/develop/lib/web3.js#L185

**Comment by ethers** [comment]
for reference, since line numbers change, the code is:
// Default to address of Config. TODO: rremove prior to genesis.
                addr = addr || '0xc6d9d2cd449a754c494264e1809c50e34d64562b';

**Comment by kumavis** [comment]
locked it to a commit https://github.com/ethereum/ethereum.js/blob/30111f7cf57570f096435a0d0f4beea9d64380ea/lib/web3.js#L185

**Comment by chevdor** [comment]
I would recommend to make branch called semething like pre_genesis and put those commits in. This way they will be ready to be applied. It seems @kumavis already has a commit for this one, if I misunderstood, I am glad to prepare a pull request for it.

A think a bunch of tests will also have to evolve after genesis.

**Comment by kumavis** [comment]
No I don't have a commit, I was just providing a better url for targeting the offending line

**Comment by chevdor** [comment]
I prepared a branch for that and whatever cleanup we need pre-genesis: https://github.com/chevdor/ethereum.js/tree/pre_genesis
