### ISSUE TITLE
Filter undefined?

### ISSUE THREAD

**Issue by simondlr** [ethereum/ethereum.js#73]
Using latest Ethereum.js (from develop).

When I do:

var eventFilter = web3.eth.filter(testContract.Event);

Says "filter" is an undefined function.

Similar

web3.eth.filter('pending').watch(function(res) {
//do stuff
});

It's not getting filter().

**Comment by debris** [comment]
try old name of this method. `web3.eth.watch`.

**Comment by simondlr** [comment]
Yeah, using watch instead atm. Is filter deprecated (or going to be)? Should it work?

**Comment by debris** [comment]
it's going to be. will be working soon ;)

**Comment by simondlr** [comment]
Awesome. Thanks @debris!

**Comment by simondlr** [comment]
Running latest develop, it is working properly. Thanks. Closing.
