### ISSUE TITLE
Garbage collector & polling?

### ISSUE THREAD

**Issue by simondlr** [ethereum/ethereum.js#75]
Hey! Not sure if this is the right place to ask (perhaps the forum is better?). #ethereum-dev isn't very lively. :). Will try here first.

When connecting to the c++ client (haven't tried this with go-ethereum), the garbage collector removes watches after 20 seconds. Looking at cpp-ethereum, it is made to do that (removes any watches that haven't been polled in 20 seconds). (https://github.com/ethereum/cpp-ethereum/blob/a783bbb5063fcc208fb8e85fc036e90eab1ae186/libethereum/Client.cpp#L601).

However, in the JS API, the polling is done every second. Is there a problem here where it doesn't connect to the cpp client to properly refresh the "lastPoll"? Or is this intended?

(Note: The event firing works properly, it's just that after 20 seconds, the watch gets garbage collected)

**Comment by simondlr** [comment]
After digging deeper, it's not the JS API. Seems to be a problem in CPP, where I've opened up an issue. https://github.com/ethereum/cpp-ethereum/issues/1138

**Comment by kumavis** [comment]
@simondlr closing this issue here if you don't mind
