### ISSUE TITLE
Will web3.eth.transact still work?

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/ethereum.js#80]
Will 'web3.eth.transact' be grandfathered in or are we all sold on 'web3.eth.sendTransaction'? Also when is fromWei and toWei being moved into master branch, any schedule on that (excuse the impatience)?

**Comment by debris** [comment]
web3.eth.sendTransaction (same for fromWei && toWei) will be merged today (late evening) into master branch. web3.eth.transact will be marked as deprecated and removed in next version
