### ISSUE TITLE
calling a contract function from js API

### ISSUE THREAD

**Issue by jgabios** [ethereum/ethereum.js#82]
Hi, I have a simple contract:
```
contract SuperProject {
int8 index;
function getNumber() returns (int8) {
 int8 next = index++;
 return next;
}
}
```
Now, I want to get that number in JS.
```
var ABI = [{"constant":false,"inputs":[],"name":"getNumber","outputs":[{"name":"","type":"int8"}],"type":"function"}];
var contractAddress = "0x11111222222222222222";
var contract = web3.eth.contract(contractAddress, ABI);
contract.call().getNumber();
```
That returns me this:
```
t {s: 1, e: 0, c: Array[1], abs: function, absoluteValue: function…}
```

Can anybody tell me how to properly interrogate the contract?

**Comment by SilentCicero** [comment]
That return seems fine, try converting the return to an int with 'parseInt()' or a string with 'String()' to see if the value is good. Also try converting it to a string and then throwing it in a 'new BigNumber(YOUR_STRING_NUM)' for later use with math operations such as: division and multiplication in JS. JS has trouble with big numbers hence the use of the BigNumber class. (Maybe a dev could shed more light on this, there is more bignums in the Eth JS API docs).

**Comment by jgabios** [comment]
parseInt(contract.call().getNumber()) says 0
contract.call().getNumber().toString(10) says "0"

**Comment by SilentCicero** [comment]
Hmm, your contract logic may be off, try this:
```contract SuperProject{
    int8 index;
    function getNumber() returns (int8 _next) {
       _next = index++;
   }
}```

JS:
var retVal = contract.call().getNumber();
console.log(String(retVal));
I got '1' with this. Also, if your contract is not deployed properly or the hex is invalid it will return '0' by default.

**Comment by jgabios** [comment]
ok,
I tried your contract too.
same thing: 0.
To check if my contract is deployed properly I do:
web3.toEth(web3.eth.balanceAt('0x80e0f7955f537d3fb6f57a39b6fde389afb957b8'))
"1000 finney"
That's 1000 finney that I put at the contract creation time.
So, I guess the contract is ok at the right address.
Below is the exact js code I use:
```
        <script>
            var contractDesc = [{"constant":false,"inputs":[],"name":"getNumber","outputs":[{"name":"_next","type":"int8"}],"type":"function"}];
            var account = "0x80e0f7955f537d3fb6f57a39b6fde389afb957b8";
            var contract = web3.eth.contract(account, contractDesc);
            var rez = contract.call().getNumber();
            console.log(String(rez));
        </script>
```

**Comment by jgabios** [comment]
I got it.
contract.call().getNumber() wasn't going to increment my index variable in the contract ever.
However, calling contract.getNumber() first - which returned "undefined", then calling contract.call().getNumber() - which returned 1, did the trick.
contract.getNumber() - actually does the transaction
contract.call().getNumber() -> you get 2
contract.getNumber()
contract.call().getNumber() -> you get 3.

**Comment by medlahbib** [comment]
if you still need help : your_result.toNumber() ;)
