### ISSUE TITLE
Same parameter name returns 0

### ISSUE THREAD

**Issue by joeykrug** [ethereum/ethereum.js#83]
Whenever I have two functions in a contract that share a parameter name, say description:str, this causes every single function in the contract to return 0 when making web3 js calls using cpp-ethereum.  

If I change one of the parameter names to something different, everything returns to working as usual.  Can we get support for same parameter name functions?  This works fine on pyethereum's tester, just not with any web3 js stuff.

Edit: this only happens with string parameters

**Comment by joeykrug** [comment]
Issue seems to have disappeared...

**Comment by caktux** [comment]
Encountering this also, reopening.

**Comment by gavofyork** [comment]
please add a test which fails.

**Comment by debris** [comment]
does it still occur?

**Comment by caktux** [comment]
nope, closing, @joeykrug feel free to reopen if it does on your end

**Comment by joeykrug** [comment]
Works on my end too!
