### ISSUE TITLE
web3.eth.getBalance(address) now returns 0

### ISSUE THREAD

**Issue by caktux** [ethereum/ethereum.js#89]
For some reason it's fine in Firefox, but Chrome and therefore AZ return 0.

**Comment by kumavis** [comment]
@caktux can you provide a little more context? what does Firefox return? what is the expect return value?

**Comment by kumavis** [comment]
maybe provide a test

**Comment by kumavis** [comment]
I'm guessing this is related to https://github.com/ethereum/ethereum.js/issues/83

**Comment by caktux** [comment]
Scratch that about Firefox. I had reverted the new API function names, and it turns out that I get the expected 1,606,938.0443 Uether using `balanceAt`, but get 0 using `getBalance`.

**Comment by kumavis** [comment]
oh weird. not sure what version you're using, but...
`balanceAt` and `getBalance` are backed by the same rpc method but `getBalance` is using an inputFormatter that i imagine is the culprit.
https://github.com/ethereum/ethereum.js/blob/develop/lib/eth.js#L48

**Comment by caktux** [comment]
Always on the latest develop if I report something. That sounds about right about getBalance using an inputFormatter and not balanceAt.

**Comment by debris** [comment]
should be fixed by now
