### ISSUE TITLE
Solidity annotations (suggestion)

### ISSUE THREAD

**Issue by androlo** [ethereum/ethereum.js#90]
Hi. I'm playing around with a system to generate ABIs from solidity contract source code, using web3. Not sure if you have already done that. Either way I will present my stuff here. What I'm doing is to allow annotations in solidity contract code, sort of like how natspec annotations work. The idea is this:

Functions, fields and contracts can have annotations above the function/contract name. Lines that has annotations in them starts with `//`, so that they are simply consumed by the solidity lexer. The annotations I'm mostly concerned with now are these:

`@accessor=val` (`val` is `true` or `false`, default value [if no accessor annotation is found] is `false`)
`@exported=val` (`val` is `true` or `false`, default value [if no exported annotation is found] is `true`)

Accessor is important as it will make the selection between using `call`and `transact` automatic, even in complex, custom accessor functions that may involve calls to other functions, and maybe even contracts.

`exported` is good too, because even if a function is public, it may be unreachable from any javascript code due to permissions. For example, certain contracts I use can only be called by other contracts in the system due to restrictions that has to do with account permissions. I don't want to have to export those functions into the javascript contract. Also, since accessor functions get names based on the field names it's simple to check the annotation on the field then just find the function with the same name in the abi.

Anyone interested in this in some way, or is perhaps working on something similar? Again sorry if something like this is right under my nose but I can't find it.

Names are of course not set in stone...

**Comment by androlo** [comment]
Another annotation that might be useful is `@json=true/false`, and in case it's true, the system will attach an interceptor that formats the call return values into a json object before returning, using the field names as specified by the function abis `outputs` array. Currently i apply these manually, but automation is the goal. What I like about this - especially in the case of structs - is that the model that is set in Solidity code is preserved basically all the way up to the webpage view. Super clean.

**Comment by kumavis** [comment]
@androlo are you building a solidity compiler or a solidity parser + abi generator?

This is not really the best place to discuss changes to Solidity, but there's not a specific repo for the project either.

cpp-ethereum seems to have the most hits for solidity
https://github.com/ethereum/cpp-ethereum/issues?q=is%3Aissue+is%3Aopen+solidity

**Comment by androlo** [comment]
it's a javascript library that generates ABIs from contract source code. Though I am sure a source-abi function will be available from web3, or maybe already is, i want to allow custom annotations to decide on what eventually ends up in the abi json file that I use in javascript. It's all javascript related, but the annotations would be in the solidity source, albeit inside single-line comments so that the regular compiler and generators are not affected.

**Comment by androlo** [comment]
The value it provides is that all the information - the complete set of information about the ABI - would be contained within the contract source files, and  no external ABI files would have to be provided with the DAPP. In my own systems the deployment is automatic, based on a javascript deployment file, but it needs both contract source files and abi json files as inputs, rather then just the contract source files. Even if I could get the 'raw' abi files through eth/aleth somehow, they are not useful as i still have to set the js contracts up manually so that some use txs and some calls when calling methods on the contract objects.

**Comment by androlo** [comment]
Actually, I have a better plan, that requires almost no lexing/parsing. If there's any interest in this ill post once it's made (which shouldn't take long).

**Comment by kumavis** [comment]
@androlo yeah please do, interested

**Comment by androlo** [comment]
Wrote the 'draft'. Of course it's something that's very much a wip... although the implementation is kind of trivial. Still depends on the ABI as returned by the 'ABI interface json' function from the compiler, but that's probably a good thing. Not going to break compatibility with the core stuff.

https://github.com/eris-ltd/decerver/issues/104

**Comment by kumavis** [comment]
@androlo we would be interested in this in `node-ethereum`, where compiling in general for all languages is still on our todo list. and i'd be interested in adding compiling to `vapor` to take load off of the server. But in both cases we'd bring it in as a module. If you're interested in building and publishing `node-solidity-compiler`, it would get a lot of use.

**Comment by androlo** [comment]
Ok. Yes so this is just a temporary solution anyways, which is why i use json and base it on the abi files that solidity already generates - to have something that is easy to maintain and use until whatever comes later can replace it.

Vapor and node-ethereum looks like really interesting initiatives, will look into it more.
