### ISSUE TITLE
IPFS integration (off-chain p2p file storage)

### ISSUE THREAD

**Issue by androlo** [ethereum/ethereum.js#91]
I did a node.js port of an [IPFS](https://github.com/jbenet/go-ipfs) file-storing module we've been using. The way it works is you call the javascript `ipfs` object to add and get files. The requests are passed on  to an ipfs server using its web api. Normally this server would be running locally - using either the normal build or the docker file - so it works the same as calling a headless ethereum client with the json-rpc server enabled.

[Here's](https://github.com/eris-ltd/decerver/issues/105) is a link to an issue.

The best way to do blockchain client - ipfs inter-op is basically to take a file, pass it to ipfs through the `ipfs.addFile` method. It will automatically return the ipfs hash as a hex string. You would then store the hash in a smart contract under a certain name. Omitting the callbacks and stuff, this would be the basic flow:

Let's say you have a smart contract that holds user data and looks something like this:
``` javascript
contract User {

   struct Avatar {
      string32 imageName;
      hash imageHash;
   }

   struct UserData {
       string32 userName;
       Avatar avatar;
   }

   UserData public userData;

function registerUser(string32 userName, string32 imageName, hash imageHash){
     userData.name = userName;
     userData.avatar.imageName = imageName;
     userData.avatar.imageHash = imageHash;
}

}
``` 

When you want to register a new user you would have a function like this in javascript:

``` javascript
function registerUser(userName, imageDir, imageName){
    var imageHash = ipfs.addFile(path.join(imageDir,imageName));
    userContract.transact().registerUser(userName,imageName,imageHash);
}
```
When you want to retrieve the data, it'd be something like this:

``` javascript
function getUser(){
    var userData = userContract.call().userData();
    var imageUrl = ipfs.getIPFSEndpoint(path.join(imageDir,imageHash));
    
    return {"user_name" : userData.userName, "avatar_image_name", userData.avatar.imageName, "avatar_image_url" : imageUrl };
}
```

This would pass the endpoint where the image can be fetched from an ipfs server to the caller, which can be practical at times, but you could just as well fetch the file data using the `ipfs.getFile(hash)` method and pass it as bytes instead.

This is just to show how it's done in practice. It's over simplified as it relies on callbacks, and also an ipfs hash is normally more then 32 bytes and may vary when starting to use folders etc., so an array of hashes or a plain 'bytes' is probably the best way of storing hashes these days. It used to be only 34 byte hashes, where the 2 first bytes were hashing algorithm info and size, so they could be cropped out before writing to a contract and prepended when getting it - as part of the functions - since they are constant. This of course made it possible to use only 1 word for each hash. Still works but only for individual file objects.

Let me know if you would be interested in this. I would like to contribute if possible. I'm using web3, setting up gulp, mocha tests etc. and I model my node.js libraries after this lib, but it's not quite there yet, so a proper pull request would take some time (need to inspect the lib more, learn your coding style and such). I've been doing a lot of this type of stuff though, in fact its my job.

**Comment by kumavis** [comment]
this is awesome! good work. is this on github somewhere?

**Comment by androlo** [comment]
Thanks!

No but I'll add it. I am still adding a small mocha test suite, so it's on the same format as the rest of the tests you have, in case a pr would eventually come into question. It should be done by tomorrow probably. I'll update the issue.

Really like the web3 namespace btw., for "the collection of future tech".

**Comment by kumavis** [comment]
let us know when you post it!

**Comment by androlo** [comment]
I put it in a repo now. I have not made it into a full module yet - that and my other code was just part of an app - but it should be possible to pull it and run 'mocha'. It's tiny.

To start an ipfs daemon you download and either install and run `ipfs init` followed by `ipfs daemon -writable`, or run the docker. It will start everything the module needs. It's in alpha. They actually have a node module coming up, but who knows when that will be ready.

Public dev from my side will be sparse btw, so I am going to back off from these things. I am not sure how licensing really works as I'm working for a company, but none of this is really out of the ordinary. it's just a few requests to a web api... but i promised this already so here it is. I strongly recommend using ipfs for off-chain storage though. Been working on Ethereum dapps for almost a year now and  off-chain file storage is essential. It is certainly the most important component after the blockchain itself. IPFS looks real promising.
