### ISSUE TITLE
ABI in web3 for serpent seems to be not working

### ISSUE THREAD

**Issue by Georgi87** [ethereum/ethereum.js#93]
The ABI definition in web3.eth* seems to be incompatible with serpent:

```javascript
var abi = [
       {
            "constant": false,
            "inputs": [{"type":"uint256", "name": "list_index"}],
            "name": "_get_current_price",
            "outputs": [{"type":"uint256", "name": "share_price"}],
            "type": "function"
        },
        {
            "constant": false,
            "inputs": [],
            "name": "get_contract_balance",
            "outputs": [{"type":"uint256"}],
            "type": "function"
        }
]
var contract = web3.eth.contract(contract_address, abi);
var contract_address = "xyz..."
web3.eth.call({"to": contract_address, "data": "0xaf11c8250000000000000...000000003e9"}));
contract.call()._get_current_price(1002);
contract.call().get_contract_balance();
```
The first and second call represent the same function and arguments. The first call that is manually encoded works, while the 2nd call fails (returns 0). However a call without any arguments works (call 3). So prefix seems to wrok, while function arguments are not encoded properly. Is my syntax wrong or is there no solution to this yet for serpent code?

**Comment by jorisbontje** [comment]
serpent has `int256` arguments by default, so update the ABI inputs accordingly; otherwise it will mess up the sha3 function signature.

**Comment by Georgi87** [comment]
Thank you very much. It works now. Anyways the dev version of serpent seems to work with uints as negative values are not possible and integers wrap at 2^256.

**Comment by Georgi87** [comment]
There is another issue with encoding of arrays. I tested a serpent function that simply adds a value to an array. E.g. [1,2,3] + 4 = [1,2,3,4]. When calling this function from serpent it returned [1,2,3,4], but calling it from web3 contract returned [2,3,4,1]. I looked into this odd behaviour and found out that the encoded data of the call was different.

This is the encoded serpent data:
ff6d501100000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003

Using serpent data in a web3 call, we get the correct response [1,2,3,4]:
0x00000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000004

The data encoded by web3 returned this: 
ff6d501100000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000004

Serpent encodes 3 (array length),4 (added value),1,2,3 while web3 encodes 3 (array length),1,2,3,4(added value).
The web3 encoding seems to make more sense, but its incompatible with the serpent dev version.

**Comment by chriseth** [comment]
The serpent way is in line with the [ABI](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI). The advantage for this encoding is that it is possible to compute the index into any array in calldata by looking only at a small prefix of the calldata.

**Comment by Georgi87** [comment]
So there is no support for array encoding in web3 for serpent code right now. Is this a known issue and planned to be fixed?

**Comment by chriseth** [comment]
It seems like #85 already fixed it. It might be that that did not yet arrive in your branch/distribution.

**Comment by debris** [comment]
cherrypicked #85 to master branch. realease 0.0.16 should be fine.
